#spring.application.name=SnapVote
#spring.data.mongodb.database=VoteDB
#spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb+srv://stduy21:F1m0HBoVlfWG7Mif@cluster0.wvhfwee.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.main.allow-circular-references=true

#username : stduy21
#password : F1m0HBoVlfWG7Mif
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB